### ISSUE TITLE
Not opening while clicked

### ISSUE THREAD

**Issue by sarthakdhakal** [sugamkarki/netflix-clone#3]
It doesn't show the details of the show when clicked. Please implement proper features by using backend programming. Otherwise, everything looks fine.

Hope to see it updated

**Comment by sugamkarki** [comment]
> @sarthakdhakal This is only a prototypical version of Netflix's user interface. What you're suggesting goes above and beyond the scope of this project. 
---
> However, if you have knowledge/idea of any free providers that give their storage service for free, then kindly drop them and I'll look into it.  
> We can also collaborate on this project to complete the features that you've said are missing.

* I'll be closing this issue *
